version: '3'
services:
  solr:
    image: 'solr:alpine'
    ports:
      - '8983:8983'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cce
  conciliator:
    build: .
    depends_on:
      - solr
    ports:
      - '8080:8080'
